### ISSUE TITLE
Alignment looks a bit strange.

### ISSUE THREAD

**Issue by laubonghaudoi** [zzossig/hugo-theme-zdoc#1]
<img width="437" alt="screencap" src="https://user-images.githubusercontent.com/11172180/74404687-0d566400-4de0-11ea-9ee4-9437f03f4c95.PNG">
Like the pic above, the distance between date/author line and and the navbar is too close. The date/author line should be placed in a better position.

**Comment by zzossig** [comment]
It's fixed 3 hours ago 50c6b66

**Comment by laubonghaudoi** [comment]
Sorry, maybe the demo site isn't updated.

**Comment by zzossig** [comment]
Yes, the demo site update every 3 days.
Anyway, thanks for the first issue!
