### ISSUE TITLE
Repeated items in list

### ISSUE THREAD

**Issue by davidmarcielp** [zzossig/hugo-theme-zdoc#14]
Hi, I am having repeated items in a list.

I have created a fourth element in the top menu, it is called Protected, the value inside is:
---
title: "Protected"
description: "test protected index"
date: 2020-01-11T14:09:21+09:00
draft: false
---

When it renders it creates two elements for each element in the folder.
I did a test removing one of the elements and it removes both copies.

This issue doesn´t happen in the other folders.

You can see it running in here:
https://davidmarcielp.github.io/davidmarcielp

and the code here:
https://github.com/davidmarcielp/davidmarcielp

**Comment by zzossig** [comment]
Hi, I can't reproduce it.
Can you show me the repository which is not `public` folder(build version) but the original site code?

**Comment by davidmarcielp** [comment]
Yes, sorry, the proper repo is: https://github.com/davidmarcielp/hugo-zdoc

**Comment by zzossig** [comment]
It's strange.
It works fine with my local environment.
![주석 2020-03-02 165934](https://user-images.githubusercontent.com/52706977/75656418-3b281d80-5ca7-11ea-9d25-e75a4ba37c5f.png)

**Comment by davidmarcielp** [comment]
Yes, it happens when I run it locally but also when I run it in a server, but only in the protected menu folder.

![image](https://user-images.githubusercontent.com/60340628/75657538-bddcb880-5c66-11ea-8726-40cf7582b03c.png)

**Comment by zzossig** [comment]
How did you start the Hugo?
Why the port number is `8080`.
The default port number is `1313`.

**Comment by davidmarcielp** [comment]
yes, in this case is using node, in this case is using hugo server:
![image](https://user-images.githubusercontent.com/60340628/75657773-3b082d80-5c67-11ea-8ff8-7ccbfc1f7fef.png)

In this case is direcly in github:
![image](https://user-images.githubusercontent.com/60340628/75657821-52471b00-5c67-11ea-88b0-6d449959d96b.png)

**Comment by davidmarcielp** [comment]
It only happens in the protected folder (next to blog)

**Comment by zzossig** [comment]
What OS are you using?
It looks fine in Windows 10.
Are you using Ubuntu?

**Comment by zzossig** [comment]
How about deleting these folders?
This is not necessary since you are using language folder
![주석 2020-03-02 175009](https://user-images.githubusercontent.com/52706977/75659960-4763a900-5cae-11ea-89c3-3df64ec804cb.png)

**Comment by davidmarcielp** [comment]
It still happens when I remove those folders 🤕 
Im using Win 10,

**Comment by zzossig** [comment]
How about delete `_index.md` file at `config/_default` folder which is not necessary.
And what Hugo version are you using?
![주석 2020-03-02 181034](https://user-images.githubusercontent.com/52706977/75661699-22bd0080-5cb1-11ea-884d-db41710e17dd.png)

**Comment by davidmarcielp** [comment]
I´ve tried everything and I couldn't find the way to make it work,
doesn´t matter, thanks for your help zzossig.
