### ISSUE TITLE
Add toggle button similar to your zzo hugo theme to 

### ISSUE THREAD

**Issue by kanthi** [zzossig/hugo-theme-zdoc#15]
It would be great to utilise all the space on the screen for documentation. your zzo theme has good toggle button option or feature to disable and utilise the space, if possible add similar options for this theme too.

**Comment by zzossig** [comment]
I made it.
Just set the param like this

`params.toml`
```toml
...
enableTocSwitch = true
```

**Comment by kanthi** [comment]
> I made it.
> Just set the param like this
> 
> `params.toml`
> 
> ```toml
> ...
> enableTocSwitch = true
> ```

@zzossig I did not find any difference after following your instructions above for toggle switch. I was talking about similar to "whats on this page" toggle button for Zdoc theme 
 
![Screenshot from 2020-03-04 19-12-15](https://user-images.githubusercontent.com/1001550/75885293-49636e80-5e4c-11ea-96dc-b83abdb6212d.png)

**Comment by zzossig** [comment]
Did you update the theme latest version?
You should see an arrow icon next to the ‘what’s on this page’

**Comment by kanthi** [comment]
Yes I have updated the theme to latest version . This is how it shows up. Can you please provide your demo please.

![Screenshot from 2020-03-04 19-22-55](https://user-images.githubusercontent.com/1001550/75886428-33ef4400-5e4e-11ea-8502-312e68902f40.png)

**Comment by zzossig** [comment]
Can I see your repository?
You can see the example here https://zzodocs.netlify.com/docs/gettingstarted/quickstart/

**Comment by kanthi** [comment]
I guess it has something to with my repo. I have copied my docs into your zzodocs repo and it seems to work as attached in the screenshot below. Thank you. I will update further once I do clean and new setup. Thank you once again for your time

regards

![Screenshot from 2020-03-05 09-12-29](https://user-images.githubusercontent.com/1001550/75945944-acdbb380-5ec1-11ea-9231-79ec83833285.png)

**Comment by zzossig** [comment]
Ok, tell me if something went wrong.

> Its very hard to decide between zzo and zdoc

It's simple. zzo made for blog and zdoc made for documentation😂

**Comment by kanthi** [comment]
> It's simple. zzo made for blog and zdoc made for documentation

My requirement is like combination of both. I like blogging part from zzo and documentation part from zdoc :-) .  Anyway great work with both of them.
