### ISSUE TITLE
Repeated file

### ISSUE THREAD

**Issue by davidmarcielp** [zzossig/hugo-theme-zdoc#17]
Hi, I have realized the search is using a file called index.json, this file is pretty big since it contains every single file encoded.

The file is used in themes/zdoc/layouts/partials/head/scripts.html:387

```
        var xhr = new XMLHttpRequest();
        xhr.open('GET', permalink + "index.json");
        xhr.setRequestHeader('Content-Type', 'application/json; charset=utf-8');
```

I have realized this file is repeated for each page, I think there is no need to repeat this file since is pretty heavy and it could be reused for every html: 

![image](https://user-images.githubusercontent.com/60340628/76086210-f1477c00-5fb3-11ea-8501-f079ba2ed571.png)

![image](https://user-images.githubusercontent.com/60340628/76086221-f7d5f380-5fb3-11ea-977a-5fa4215941bc.png)

![image](https://user-images.githubusercontent.com/60340628/76086240-02908880-5fb4-11ea-8858-f619ba6543b8.png)

I think public folder would be much lighter with this enhancement, it could also run faster.

As a suggestion, another approach would be to store just the folder information on it so your searches would work only in this folder and subfolders and filter this way the search.

Regards and Congrats for such a beautifull theme.

**Comment by zzossig** [comment]
Hi,
You can make fewer search indexes by doing this.

In your `config.toml` file
```
...
[outputs]
  home = ["HTML", "RSS", "SearchIndex"]
```

And after update the theme you can get fewer search indexes
