### ISSUE TITLE
Search function does not work in public folder(push to github)

### ISSUE THREAD

**Issue by cao-arvin** [zzossig/hugo-theme-zdoc#18]
Files in public folder Search function does not work. But running locally by "hugo serve" is fine.

My blog url: https://www.wenhui.space/

**Comment by zzossig** [comment]
Set baseURL in your `config.toml` file to `https://www.wenhui.space` (or `https://wenhui.space`)
![주석 2020-03-08 143103](https://user-images.githubusercontent.com/52706977/76157245-83cd5400-6149-11ea-87ee-0b32c13856f0.png)

The error occurred because you are using custom URL

**Comment by cao-arvin** [comment]
Thanks
