### ISSUE TITLE
Can you support searching with hugo-lunr-zh?

### ISSUE THREAD

**Issue by cpiqq** [zzossig/hugo-theme-zdoc#19]
I like this topic very much, but for documentation, search is so important. I tried to integrate hugo-lunr-zh myself, but it failed because I am not a web developer, and there is too little information on the Internet. Now my first resistance to using this theme is the Chinese search function. So, could you please support hugo-lunr-zh search? I will be very grateful! !!

**Comment by zzossig** [comment]
No, sorry.
I was tried and failed.
The lunr seems to not very working well with CJK languages(Chinese, Korean, Japanese)
