### ISSUE TITLE
Shortcode style and documentation

### ISSUE THREAD

**Issue by MickaelVanhoutte** [zzossig/hugo-theme-zdoc#20]
Hi, 

First of all, thank you for this nice and clean theme !

I'm a bit struggling to use it correctly though because of the missing documentation (landing, cards, blog ... ) do you plan to add it soon or later ?

I also see that you added shortcodes for notices that i would like to use but no css exists for the class "notices", is it a work in progress ?

Thank you !

**Comment by zzossig** [comment]
Thanks,
I'll do it this weekend.

**Comment by MickaelVanhoutte** [comment]
Nice, thank you. 
To wait until you add it i used the style from Hugo Learn Theme that looks like this : 
`
div.notices {
    margin: 2rem 1rem;
    position: relative;
}
div.notices p {
    padding: 15px;
    display: block;
    font-size: 1rem;
    margin-top: 0rem;
    margin-bottom: 0rem;
    color: #666;
}
div.notices p:first-child:before {
    position: absolute;
    top: 2px;
    color: #fff;
    left: 10px;
}
div.notices p:first-child:after {
    position: absolute;
    top: 2px;
    color: #fff;
    left: 2rem;
}
div.notices p {
    border-top: 30px solid #6AB0DE;
    background: #E7F2FA;
}
div.notices p:first-child:after {
    content: 'Info';
}
`
If it may help.

**Comment by zzossig** [comment]
I added the shortcode 
https://github.com/zzossig/hugo-theme-zdoc#shortcodes

**Comment by MickaelVanhoutte** [comment]
Perfect, thank you !
