### ISSUE TITLE
long toc not scrolling properly

### ISSUE THREAD

**Issue by rgr19** [zzossig/hugo-theme-zdoc#23]
Hi! With long toc and hovering with pointer over it, then scrolling, toc is not scroller, but content is. Dunno if its issue or not existing feature. Anyway please fix it asap :D haha. Nah I'm kidding, but it would be nice if You would think about it.

**Comment by zzossig** [comment]
Sorry for late.
It's fixed in d7c5ec7bd0b5a009fa846d13f79c61d25842e93e
