### ISSUE TITLE
Content on the landing page?

### ISSUE THREAD

**Issue by pwinston** [zzossig/hugo-theme-zdoc#25]
I've trying add content to the main/landing page. If I add markup to the bottom of `exampleSite/content/en/_index.md` it doesn't show up anywhere. Is there a way to get content on the main/landing page? Thanks.

**Comment by Abdelalihub** [comment]
> I've trying add content to the main/landing page. If I add markup to the bottom of `exampleSite/content/en/_index.md` it doesn't show up anywhere. Is there a way to get content on the main/landing page? Thanks.

Same here!

**Comment by Abdelalihub** [comment]
Hi,
In case you still have that issue. check this closed issue #3. 
You can  replace the  `/content/en/_index.md`  file with the example code mentioned in [here](https://github.com/zzossig/hugo-theme-zdoc/issues/3#issuecomment-589559863).
Your landing page should look like in here https://zzodocs.netlify.com/ .

**Comment by caspii** [comment]
This needs to be documented in the `README.md`

**Comment by sylnsr** [comment]
Cant get the landing page to work at all. Ditching this theme for something that works.

**Comment by zzossig** [comment]
Sorry for late. 
I have documented it in doc site - https://zzo-docs.vercel.app/zdoc/pages/home/
Check the full code in the file at `exampleSite/content/en/_index.md` file.
