### ISSUE TITLE
Long titles make sidebar text crowded

### ISSUE THREAD

**Issue by yanmarvin** [zzossig/hugo-theme-zdoc#27]
When the title is too long, for example:
`title: "abc def abc def abc def abc def abc def abc def abc def"`
The title shown in the sidebar overlaps with other titles, especially when there are multiple long titles on besides. Is there a good way to add some spaces between titles? Or an alternative shorten title can be set? Thanks!

**Comment by zzossig** [comment]
It's fixed in 5cb148bab9a190431dab408d375b99843d59a7c5.
Thanks!
