### ISSUE TITLE
code tabs [feature request]

### ISSUE THREAD

**Issue by jadarve** [zzossig/hugo-theme-zdoc#33]
It would be really nice to have support for code tabs to support projects with APIs for different programming languages.

I have tried the approach of https://github.com/rvanhorn/hugo-dynamic-tabs. While it works, the CSS starts to get broken as I need to include bootstrap to make the tabs working.

I can help developing the feature, with some guidance.

**Comment by zzossig** [comment]
Sorry for late.
I have added it in recent commits.
Update the theme first.
Check https://zzo-docs.vercel.app/zdoc/shortcodes/codeblock/
