### ISSUE TITLE
deprecation warning re !global assignments when build

### ISSUE THREAD

**Issue by abulka** [zzossig/hugo-theme-zdoc#34]
I'm getting the deprecation warning

```
Start building sites … 
DEPRECATION WARNING on line 4 of /Users/andy/Devel/hugo_tests/quickstart/themes/zzo/assets/sass/abstracts/_mixins.scss:
!global assignments won't be able to declare new variables in future versions.
Consider adding `$theme-map: null` at the top level.
```

each time I serve or build with Hugo.  Is there a fix for this?

**Comment by zzossig** [comment]
It is fixed in 71d26cb

In this documentation - https://sass-lang.com/documentation/variables#shadowing
>Older Sass versions allowed !global to be used for a variable that doesn’t exist yet. This behavior was deprecated to make sure each stylesheet declares the same variables no matter how it’s executed.

So, I declared the global variable at the top of the scss file

```scss
$theme-map: null;
@mixin themify($themes) {
...
```
And it breaks nothing
