### ISSUE TITLE
This endpoint is deprecated. Please read https://developers.facebook.com/docs/instagram/oembed to learn how to migrate your endpoint.

### ISSUE THREAD

**Issue by dyingway** [zzossig/hugo-theme-zdoc#37]
ERROR 2020/11/05 21:24:07 Failed to get JSON resource "https://api.instagram.com/oembed/?url=https://www.instagram.com/p/BGvuInzyFAe/&amp;maxwidth=640&amp;omitscript=true": Failed to retrieve remote file: Bad Request
If you feel that this should not be logged as an ERROR, you can ignore it by adding this to your site config:
ignoreErrors = ["error-remote-getjson"]

============================
add ignoreErrors = ["error-remote-getjson"],and the server work,but i still think i should report this issues.

i like this theme,thank you.

**Comment by zzossig** [comment]
Thanks for the information😋.
For now, I just deleted the Instagram shortcode.
