### ISSUE TITLE
[Question] Why the table has no borders

### ISSUE THREAD

**Issue by ayalhw** [zzossig/hugo-theme-zdoc#38]
As title, it looks like this
![图片](https://user-images.githubusercontent.com/43064781/98252448-eb77bf80-1fb4-11eb-9458-1480daba16fe.png)
using Markdown Code:
```markdown
| aaaa | bbbbb |
| :----: | :----: |
| ccccc| ddddd|
```
No other configuration except basic configuration

**Comment by zzossig** [comment]
It seems you mean a section pages.
I'll fix it soon.

**Comment by zzossig** [comment]
It's fixed in 574f6c3

**Comment by CoelacanthusHex** [comment]
thx
