### ISSUE TITLE
Difference between zdoc and zzo theme

### ISSUE THREAD

**Issue by franc23** [zzossig/hugo-theme-zdoc#4]
In the interest of keeping things in one place, what's the difference between https://github.com/zzossig/hugo-theme-zzo/ and https://github.com/zzossig/hugo-theme-zdoc/

gohugo had zdoc listed higher in the theme listings, but zzo has more contributors and active commits.

**Comment by zzossig** [comment]
zzo theme is 4 months old. and zdoc theme is 1months old.
zzo theme is blog theme. and zdoc theme is documentation theme.
zzo theme is older so it has more contributors.
Hugo theme maintainers determine the theme listing order. So I don't know why is it listing like that.

**Comment by laubonghaudoi** [comment]
I have an additional question, what theme does [this site](https://zzodocs.netlify.com/) use? I looks like a zdoc theme but the homepage is different, with a "why zdoc" ribbon.

**Comment by zzossig** [comment]
Actually, I'm testing the zdoc theme on the site.
The landing page(home section page) is currently in development there.
But I'm busy these days so it's not going to be quick delivery.

I'm thinking to imitate some concept from https://www.rust-lang.org/
