### ISSUE TITLE
Doc Pagination Link Order

### ISSUE THREAD

**Issue by jacksloan** [zzossig/hugo-theme-zdoc#5]
Thanks for the great theme!

The bottom navigation links appear to be in reverse order even when "languagedir" setting is not rtl.
For example, on the example site configuration page I would expect "Basic Usage" to be on the left and "Installation" to be on the right.

<img width="1026" alt="Screen Shot 2020-02-19 at 11 25 05 AM" src="https://user-images.githubusercontent.com/17889993/74858200-8a1a9e00-530a-11ea-821e-05196279f502.png">

**Comment by zzossig** [comment]
It's fixed now!
Thank you for noticing it to me
