### ISSUE TITLE
Any plans for new integrations? MermaidJS, KaTeX, etc..

### ISSUE THREAD

**Issue by sgama** [zzossig/hugo-theme-zdoc#6]
I was wondering if there are any plans to add integrations such as MermaidJS, KaTeX and charts like in the zzo theme. https://github.com/zzossig/hugo-theme-zzo

Thanks for open-sourcing your theme.

**Comment by zzossig** [comment]
I have a plan to make something when I requested it.
I'll do it this weekend

**Comment by zzossig** [comment]
Now the Zdoc theme support `mermaid`, `katex`, `mathjax`, `chart`, `flowchartjs`
You can reference this link https://zzodocs.netlify.com/docs/externallibrary/

**Comment by laubonghaudoi** [comment]
I tried the mermaid and flowchartjs but they don't render, they are just displayed as code blocks like the screen cap below. Could you please give an example how to make them rendered?
![image](https://user-images.githubusercontent.com/11172180/75116626-34523880-561f-11ea-992a-9e60fd092157.png)

**Comment by zzossig** [comment]
Can you show me the full md file?

**Comment by laubonghaudoi** [comment]
I am copy pasting exactly the same codes in your doc:

```markdown
---
title: demo
date:
description:
...
libraries:
- mermaid
---

```mermaid
graph TD;
  A-->B;
  A-->C;
  B-->D;
  C-->D;
```

```mermaid
sequenceDiagram
  participant Alice
  participant Bob
  Alice->John: Hello John, how are you?
  loop Healthcheck
      John->John: Fight against hypochondria
  end
  Note right of John: Rational thoughts <br/>prevail...
  John-->Alice: Great!
  John->Bob: How about you?
  Bob-->John: Jolly good!
```

```mermaid
graph TD
A[Hard] -->|Text| B(Round)
B --> C{Decision}
C -->|One| D[Result 1]
C -->|Two| E[Result 2]
```

```mermaid
gantt
section Section
Completed :done,    des1, 2014-01-06,2014-01-08
Active        :active,  des2, 2014-01-07, 3d
Parallel 1   :         des3, after des1, 1d
Parallel 2   :         des4, after des1, 1d
Parallel 3   :         des5, after des3, 1d
Parallel 4   :         des6, after des4, 1d
```

```mermaid
classDiagram
Class01 <|-- AveryLongClass : Cool
<<interface>> Class01
Class09 --> C2 : Where am i?
Class09 --* C3
Class09 --|> Class07
Class07 : equals()
Class07 : Object[] elementData
Class01 : size()
Class01 : int chimp
Class01 : int gorilla
class Class10 {
  <<service>>
  int id
  size()
}
```

```mermaid
stateDiagram
[*] --> Still
Still --> [*]
Still --> Moving
Moving --> Still
Moving --> Crash
Crash --> [*]
```

```mermaid
pie
"Dogs" : 386
"Cats" : 85
"Rats" : 15 
```
```

**Comment by laubonghaudoi** [comment]
Here is a screen cap of my file:
![image](https://user-images.githubusercontent.com/11172180/75116773-92cbe680-5620-11ea-9ff6-85042e6505fc.png)

**Comment by zzossig** [comment]
You should delete `...`

**Comment by laubonghaudoi** [comment]
Thank you! A stupid mistake.
