### ISSUE TITLE
Most of the shortcodes don't work

### ISSUE THREAD

**Issue by laubonghaudoi** [zzossig/hugo-theme-zdoc#7]
The shortcodes [](https://zzodocs.netlify.com/docs/shortcodes/alert/), [box](https://zzodocs.netlify.com/docs/shortcodes/box/), [code](https://zzodocs.netlify.com/docs/shortcodes/codeblock/), [notice](https://zzodocs.netlify.com/docs/shortcodes/notice/), [tab](https://zzodocs.netlify.com/docs/shortcodes/tab/) don't work at all. I copy the codes on your doc:
![image](https://user-images.githubusercontent.com/11172180/75118297-c3664d00-562d-11ea-8b3c-14e08abf0003.png)
But it is rendered like this:
![image](https://user-images.githubusercontent.com/11172180/75118309-d842e080-562d-11ea-9120-5cc9ef3faca7.png)
Same as other shortcodes.

**Comment by zzossig** [comment]
The doc is for the zzo theme not zdoc theme. You should know that. I didn’t document it in readme file that means it’s not supported yet

**Comment by laubonghaudoi** [comment]
Sorry, didn't realize that it is the doc of zzo theme, thought it was the doc of zdoc. Hope these features be supported soon.

**Comment by zzossig** [comment]
I'll add it one by one.
Since the UI is different from the Zzo theme, there will be additional styling jobs.

**Comment by laubonghaudoi** [comment]
Thank you, in addition please support [graph viz](https://themes.gohugo.io//theme/hugo-theme-zzo/en/posts/test-viz/) too. This will be very helpful.
