### ISSUE TITLE
Multi Level Navigation for side menu docs(Feature request)

### ISSUE THREAD

**Issue by kanthi** [zzossig/hugo-theme-zdoc#8]
Hi 

Thank you for this theme , its most suited for needs off all the themes I have tried. 
Any how It would be great if multilevel side menu navigation is possible . As my docs tree structure is as follows . 
.
├── _index.md
└── Linux
    ├── Guides
    │   ├── Commands
    │   │   ├── Archieving-Compression
    │   │   │   ├── bzip2.md
    │   │   │   ├── cpio.md
    │   │   │   ├── dd.md
    │   │   ├── Environment
    │   │   │   ├── env.md
    │   │   │   ├── export.md
    │   │   │   ├── _index.md
    │   │   │   └── printenv.md

**Comment by zzossig** [comment]
I did try this before.
I remember this was not an easy job.
I'll try it this weekend

**Comment by zzossig** [comment]
@kanthi Hey are you still waiting for the feature?
I finally made it.
You can reference this link https://github.com/zzossig/zzoDocs/tree/master/content/en/docs/gettingstarted

In the link, you can see the depth folders.
That is how you can make a multi-level menu.
But keep in mind that there is a limitation - You don't have to make the same filename.
All MD files should have a different filename

**Comment by kanthi** [comment]
> @kanthi Hey are you still waiting for the feature?
> I finally made it.
> You can reference this link https://github.com/zzossig/zzoDocs/tree/master/content/en/docs/gettingstarted
> 
> In the link, you can see the depth folders.
> That is how you can make a multi-level menu.
> But keep in mind that there is a limitation - You don't have to make the same filename.
> All MD files should have a different filename

@zzossig Thank you for your time on this feature . I think I am ok with the limitations for my requirements . Will update soon with my experience.
