### ISSUE TITLE
images router wrong when baseUrl has subpath like http://x.x.x./me

### ISSUE THREAD

**Issue by luckywinds** [zzossig/hugo-theme-zdoc#9]
images in markdown must write like `![alt](/me/images/language/x.x.x.x.png)`, but `/me` should not be here

**Comment by zzossig** [comment]
It's fixed now!
I added render-hooks for the sub-path(/me).
You can find the hooks file at `root/themes/zdoc/layouts/_default/_markup`.
I did just a minimum usage. So, you can customize it as much as you want. 

like this

```
<a href="/me{{ .Destination | safeURL }}"{{ with .Title}} title="{{ . }}"{{ end }}{{ if strings.HasPrefix .Destination "http" }} target="_blank"{{ end }}>{{ .Text | safeHTML }}</a>
```

You can just use default hooks. It works well anyway
